events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server {
    listen 80;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    location / {
      add_header Cache-Control "no-store";
      try_files $uri /index.html;
    }

    location ~* \.(js|css|svg|png|jpg|jpeg|ico)$ {
      add_header Cache-Control "public, max-age=31536000, immutable";
      try_files $uri =404;
    }
  }
}
